apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: currencyservice-allow-from-frontend-and-checkout
spec:
  podSelector:
    matchLabels:
      app: currencyservice
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
        - podSelector:
            matchLabels:
              app: checkoutservice
      ports:
        - protocol: TCP
          port: 7000
