apiVersion: v1
kind: ConfigMap
metadata:
  name: hd-demo-config
  labels:
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/managed-by: k8s-hd-custom
data:
  # Non-sensitive config to demonstrate config externalization.
  ENVIRONMENT_NAME: "sit727-hd"
  DEMO_MODE: "true"
  LOG_LEVEL: "info"
