apiVersion: v1
kind: Secret
metadata:
  name: payment-demo-credentials
  labels:
    app.kubernetes.io/part-of: online-boutique
    app.kubernetes.io/managed-by: k8s-hd-custom
type: Opaque
stringData:
  # Dummy value for demo purposes only (do NOT use real credentials in git).
  PAYMENT_API_KEY: "hd-demo-fake-key-please-rotate"
